### ISSUE TITLE
1주차 과제: JVM은 무엇이며 자바 코드는 어떻게 실행하는 것인가

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/Spring-Boot-Study#1]
- JVM이란 무엇인가
- 컴파일 하는 방법
- 실행하는 방법
- 바이트코드란 무엇인가
- JIT 컴파일러란 무엇이며 어떻게 동작하는지
- JVM 구성 요소
- JDK와 JRE의 차이

위 내용에 대해 정리한 글을 코멘트로 남기기

~ 2022.01.11 마감

**Comment by jungyoonoh** [comment]
1주차 토픽
https://goofy-limburger-3f3.notion.site/JVM-6abe23511a134ca8a5c16084101a5701

**Comment by Acver14** [comment]
1주차 정리
[https://acver.tistory.com/entry/whiteshiplive-study1주차-과제-JVM은-무엇이며-자바-코드는-어떻게-실행하는-것인가](url)
