### ISSUE TITLE
6주차 과제: 상속

### ISSUE THREAD

**Issue by Acver14** [jungyoonoh/Spring-Boot-Study#11]
# 목표
자바의 상속에 대해 학습하세요.

## 학습할 것
- 자바 상속의 특징
- super 키워드
- 메소드 오버라이딩
- 다이나믹 메소드 디스패치 (Dynamic Method Dispatch)
- 추상 클래스
- final 키워드
- Object 클래스
----

**Comment by jungyoonoh** [comment]
https://goofy-limburger-3f3.notion.site/f01a37451fc54aebb230fb44e7e83c81

**Comment by Acver14** [comment]
https://acver.tistory.com/entry/JAVA상속
