### ISSUE TITLE
7주차 과제: 패키지

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/Spring-Boot-Study#14]
# 목표

자바의 패키지에 대해 학습하세요.

## 학습할 것
- package 키워드
- import 키워드
- 클래스패스
- CLASSPATH 환경변수
- classpath 옵션
- 접근지시자

**Comment by jungyoonoh** [comment]
https://goofy-limburger-3f3.notion.site/5a04dacb5d564a9587e70b05cc16ed80

**Comment by Acver14** [comment]
https://acver.tistory.com/entry/JAVA-패키지
