### ISSUE TITLE
8주자 과제: 인터페이스

### ISSUE THREAD

**Issue by Acver14** [jungyoonoh/Spring-Boot-Study#15]
# 목표

자바의 인터페이스에 대해 학습하세요.

## 학습할 것 (필수)

- 인터페이스 정의하는 방법
- 인터페이스 구현하는 방법
- 인터페이스 레퍼런스를 통해 구현체를 사용하는 방법
- 인터페이스 상속
- 인터페이스의 기본 메소드 (Default Method), 자바 8
- 인터페이스의 static 메소드, 자바 8
- 인터페이스의 private 메소드, 자바 9

**Comment by jungyoonoh** [comment]
https://goofy-limburger-3f3.notion.site/9a6a7d25f7c249c8a1d81396dc7d4cd7

**Comment by Acver14** [comment]
https://acver.tistory.com/entry/JAVA인터페이스
