### ISSUE TITLE
9주차 과제: 예외처리

### ISSUE THREAD

**Issue by Acver14** [jungyoonoh/Spring-Boot-Study#16]
# 목표

자바의 패키지에 대해 학습하세요.

## 학습할 것

- 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
- 자바가 제공하는 예외 계층 구조
- Exception과 Error의 차이는?
- RuntimeException과 RE가 아닌 것의 차이는?
- 커스텀한 예외 만드는 방법

**Comment by Acver14** [comment]
https://acver.tistory.com/entry/JAVA-예외-처리

**Comment by jungyoonoh** [comment]
https://goofy-limburger-3f3.notion.site/0a3095ac49a94e3390ff328874e70726
