### ISSUE TITLE
10주차 과제: 멀티쓰레드 프로그래밍

### ISSUE THREAD

**Issue by Acver14** [jungyoonoh/Spring-Boot-Study#17]
# 목표

자바의 멀티쓰레드 프로그래밍에 대해 학습하세요.

## 학습할 것

- Thread 클래스와 Runnable 인터페이스
- 쓰레드의 상태
- 쓰레드의 우선순위
- Main 쓰레드
- 동기화
- 데드락

**Comment by Acver14** [comment]
https://acver.tistory.com/entry/JAVA멀티쓰레드-프로그래밍

**Comment by jungyoonoh** [comment]
https://goofy-limburger-3f3.notion.site/286c1ade29e145de8542dfaafff1dea8
