### ISSUE TITLE
11주차 과제: Enum

### ISSUE THREAD

**Issue by Acver14** [jungyoonoh/Spring-Boot-Study#18]
# 목표

자바의 열거형에 대해 학습하세요.

## 학습할 것

- enum 정의하는 방법
- enum이 제공하는 메소드 (values()와 valueOf())
- java.lang.Enum
- EnumSet

**Comment by Acver14** [comment]
https://acver.tistory.com/entry/JAVA-ENUM

**Comment by jungyoonoh** [comment]
https://goofy-limburger-3f3.notion.site/Enum-3cf9acfda0f84c0893139540d916ab7a
