### ISSUE TITLE
12주차 과제: Annotation

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/Spring-Boot-Study#19]
# 목표
자바의 Annotation에 대해 학습하세요.

# 학습할 것 (필수)
- Annotation 정의하는 방법
- @retention
- @target
- @documented
- Annotation 프로세서

**Comment by Acver14** [comment]
https://acver.tistory.com/entry/JAVA-Annotation

**Comment by jungyoonoh** [comment]
https://goofy-limburger-3f3.notion.site/Annotation-21dda284d6774d49bd5a449e298515f6
