### ISSUE TITLE
2주차 과제: 자바 데이터 타입, 변수 그리고 배열

### ISSUE THREAD

**Issue by Acver14** [jungyoonoh/Spring-Boot-Study#2]
- 프리미티브 타입 종류와 값의 범위 그리고 기본 값
- 프리미티브 타입과 레퍼런스 타입
- 리터럴
- 변수 선언 및 초기화하는 방법
- 변수의 스코프와 라이프타임
- 타입 변환, 캐스팅 그리고 타입 프로모션
- 1차 및 2차 배열 선언하기
- 타입 추론, var

**Comment by Acver14** [comment]
2주차 : https://acver.tistory.com/entry/whiteshiplive-study2주차-과제-자바-데이터-타입-변수-그리고-배열

**Comment by jungyoonoh** [comment]
2주차 과제
https://goofy-limburger-3f3.notion.site/3930ac27d2004af8beb92103d28bc860
