### ISSUE TITLE
13주차 과제: I/O

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/Spring-Boot-Study#20]
# 목표
자바의 Input과 Ontput에 대해 학습하세요.

# 학습할 것
- 스트림 (Stream) / 버퍼 (Buffer) / 채널 (Channel) 기반의 I/O
- InputStream과 OutputStream
- Byte와 Character 스트림
- 표준 스트림 (System.in, System.out, System.err)
- 파일 읽고 쓰기

**Comment by jungyoonoh** [comment]
https://goofy-limburger-3f3.notion.site/I-O-bb2b9dc3e2da482bbc613d28fce5a3a8

**Comment by Acver14** [comment]
https://acver.tistory.com/entry/JAVA-IO
