### ISSUE TITLE
4주차 과제: 제어문

### ISSUE THREAD

**Issue by jungyoonoh** [jungyoonoh/Spring-Boot-Study#4]
# 목표
자바가 제공하는 제어문을 학습하세요.

----
## 학습할 것 
- 선택문
- 반복문
- JUnit 5 (개념, 어노테이션) 
----
### 과제 1. LinkedList를 구현하세요.
- LinkedList에 대해 공부하세요.
- 정수를 저장하는 ListNode 클래스를 구현하세요.
- ListNode add(ListNode head, ListNode nodeToAdd, int position)를 구현하세요.
- ListNode remove(ListNode head, int positionToRemove)를 구현하세요.
- boolean contains(ListNode head, ListNode nodeTocheck)를 구현하세요.
### 과제 2. Stack을 구현하세요.
- int 배열을 사용해서 정수를 저장하는 Stack을 구현하세요.
- void push(int data)를 구현하세요.
- int pop()을 구현하세요.
### 과제 3. 앞서 만든 ListNode를 사용해서 Stack을 구현하세요.
- ListNode head를 가지고 있는 ListNodeStack 클래스를 구현하세요.
- void push(int data)를 구현하세요.
- int pop()을 구현하세요.
### 과제 4. Queue를 구현하세요.
- 배열을 사용해서 한번
- ListNode를 사용해서 한번.

**Comment by jungyoonoh** [comment]
https://www.notion.so/JUnit5-4ede0f8ca93e4ed586e500099bc2be33

**Comment by Acver14** [comment]
https://acver.tistory.com/entry/whiteshiplive-study4주차-과제-제어문
